### ISSUE TITLE
"Too many open files" exception

### ISSUE THREAD

**Issue by fauria** [docker-library/elasticsearch#102]
**Elasticsearch version**: 2.3.2 (Dockerfile elasticsearch:latest)

**JVM version**: openjdk version "1.8.0_72-internal"

**OS version**: Docker image: https://hub.docker.com/_/elasticsearch/

**Description of the problem including expected versus actual behavior**: 
Expected behavior: An elasticsearch docker container successfully started.
Actual behavior: An elasticsearch docker container fails to start.

**Steps to reproduce**:
1. Run ```docker pull elasticsearch``` 
2. Run ```docker run -i -t --rm -v /srv/elasticseach/data:/usr/share/elasticsearch/data -v /srv/elasticseach/config:/usr/share/elasticsearch/config elasticsearch```
3. A java.nio.file.FileSystemException is raised with message "Too many open files". 

**Provide logs (if relevant)**:
http://pastebin.com/raw/kf0LDGxD

On my host environment, both hard and soft limits are greater than 65536:

```ulimit -Hn && ulimit -Sn```
```
98304
98304
```

However inside the container:

```docker run -i -t --rm elasticsearch bash```
```ulimit -Hn && ulimit -Sn```
```
4096
1024
```

**Comment by fauria** [comment]
I know, it was opened by me as well. 

It was closed because "_the "official" Docker image on Docker Hub is not affiliated with Elastic_".

Is it ok for you if I fork this repo, fix ```sysctl.conf```and pull request?

**Comment by yosifkit** [comment]
This is not an issue with the image, but is inherited from the ulimits set on the docker daemon (`--default-ulimit`). It is also settable on [`docker run`](https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container-ulimit).

**Comment by fauria** [comment]
Thanks so much!

If anyone has the same problem, I fixed it by running the container with ```--ulimit nofile=98304:98304```command line option, i.e.:

```docker run -d --ulimit nofile=98304:98304 --name elasticsearch ... ```
