### ISSUE TITLE
alpha3 isnt available on hub

### ISSUE THREAD

**Issue by easyrasta** [docker-library/elasticsearch#104]

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check the "library/elasticsearch" manifest file in the docker-library/official-images repo, especially PRs with the "library/elasticsearch" label on that repo. For more information about the official images process, see the docker-library/official-images readme.
> \- [readme.md](https://github.com/docker-library/elasticsearch/blob/82ace8b3760e3a8ddbadf90a645c99c7940ce250/README.md)

**Comment by tianon** [comment]
Will be available shortly: https://github.com/docker-library/official-images/pull/1812

**Comment by owjprice** [comment]
@tianon It seems that alpha3 still isnt available on hub.  Any ideas?

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/1809#issuecomment-224673897 :cry:
> Sorry about that. The build server was in the middle of building `neo4j` and a some other images when the server was unexpectedly restarted.  When the server came up, docker did not because there was corruption in the docker graph and we were unable to recover it. Since we cannot pull build cache (https://github.com/docker/docker/issues/20316) we are working to rebuild all of the images to fill the server again.
> 
> Once everything is built we'll push up `neo4j` and the images that were new.  Hopefully they will be up by this evening.

**Comment by owjprice** [comment]
Thanks for the heads up....hopefully it gets resolved soon...I gave it another shot this morning and still no joy 😭
