### ISSUE TITLE
Disable memory swapping

### ISSUE THREAD

**Issue by Doweig** [docker-library/elasticsearch#116]
Hello guys,

I am currently trying to optimize Elasticsearch in production.
I have noticed that is it recommended to disable memory swapping in production and the official documentation is giving 3 ways to accomplish that:

https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html#_swapping_is_the_death_of_performance

1- `sudo swapoff -a` + edit `/etc/fstab`
2- Change the `sysctl` value, `vm.swappiness = 1`
3- Change java options by editing `elasticsearch.yml`, `bootstrap.mlockall: true`

Inside the docker image however, none of there 3 ways have been implemented

Is it something that should be handled on docker level or on the host level ?

Thank you in advance guys!

**Comment by liuchong** [comment]
http://stackoverflow.com/questions/24318543/how-to-set-ulimit-file-descriptor-on-docker-container-the-image-tag-is-phusion
is this helpful? :new_moon_with_face: 
try something like:
docker run --ulimit memlock=4000000000:4000000000 -p 9200:9200 elasticsearch elasticsearch -Des.bootstrap.mlockall=true -Des.cluster.name="test"

also:
https://docs.docker.com/engine/reference/commandline/run/#/set-ulimits-in-container-ulimit
https://coreos.com/os/docs/latest/customizing-docker.html

**Comment by patrickleet** [comment]
I also can't get this to work in a Docker container. Seems like the instructions are for everything except Alpine linux, which is what the official image is on.

**Comment by Doweig** [comment]
Nope

**Comment by gjobin** [comment]
Stuck on the same issue. Anybody ?

**Comment by elianka** [comment]
+1

**Comment by tianon** [comment]
Only the third of the suggested fixes is possible within a container -- the first two need to be completed on the container host instead.

As for changing the default options, we try to stick as close as possible to what upstream provides.

**Comment by mario56** [comment]
someone find any solutions for this?

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
