### ISSUE TITLE
Upgrade elasticsearch version to 5.0.0-beta1

### ISSUE THREAD

**Issue by liweinan0423** [docker-library/elasticsearch#120]
Can we build a new image `elasticsearch:5.0.0-beta1` that contains the latest elasticsearch version of 5.0.0-beta1?

**Comment by yosifkit** [comment]
We have to wait until it is available via the elasticsearch.org apt repo.

**Comment by yosifkit** [comment]
Scratch that, it looks like they have a new repo as noted in https://github.com/docker-library/kibana/pull/55.  So we are waiting for the signing to be fixed.

**Comment by tianon** [comment]
This has been fixed for a little while now.  We'll have 5.0 GA shortly too. :+1:
