### ISSUE TITLE
Installing marvel - failed to download out of all possible locations

### ISSUE THREAD

**Issue by tarunendra** [docker-library/elasticsearch#125]
I'm trying to install marvel plugin on my elastic search on docker, below is dockerfile - 
FROM elasticsearch
ADD elasticsearch.yml /elasticsearch/config/elasticsearch.yml
RUN /usr/share/elasticsearch/bin/plugin install license
RUN /usr/share/elasticsearch/bin/plugin install marvel-agent
RUN /usr/share/elasticsearch/bin/plugin install marvel

getting below issues when i trying to do docker build - 

Sending build context to Docker daemon 4.608 kB
Step 1 : FROM elasticsearch
 ---> 22287ab1f811
Step 2 : ADD elasticsearch.yml /elasticsearch/config/elasticsearch.yml
 ---> Using cache
 ---> e35185f6ba77
Step 3 : RUN /usr/share/elasticsearch/bin/plugin install license
 ---> Using cache
 ---> 79d17dddbd2e
Step 4 : RUN /usr/share/elasticsearch/bin/plugin install marvel-agent
 ---> Using cache
 ---> 65342dc7c02d
Step 5 : RUN /usr/share/elasticsearch/bin/plugin install marvel
 ---> Running in d54312b6cf12
-> Installing marvel...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel/2.4.1/marvel-2.4.1.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
The command '/bin/sh -c /usr/share/elasticsearch/bin/plugin install marvel' returned a non-zero code: 74

**Comment by yosifkit** [comment]
Looks like it might need to be `elasticsearch/marvel`. https://github.com/docker-library/elasticsearch/issues/19#issuecomment-122112623

**Comment by tarunendra** [comment]
Thanks for your quick response, I tried changing as per your suggestion. download location seems changed but I'm still facing same issue.

Step 5 : RUN /usr/share/elasticsearch/bin/plugin install elasticsearch/marvel
 ---> Running in fe2346a0e690
-> Installing elasticsearch/marvel...
Trying https://github.com/elasticsearch/marvel/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
The command '/bin/sh -c /usr/share/elasticsearch/bin/plugin install elasticsearch/marvel' returned a non-zero code: 74

**Comment by yosifkit** [comment]
Oh, it seems that according to [these docs](https://www.elastic.co/guide/en/marvel/2.4/installing-marvel.html) you only need `license` and `marvel-agent` on the elasticsearch node.  The `marvel` plugin is installed on the kibana node.

**Comment by tarunendra** [comment]
Thank you,
