### ISSUE TITLE
Can anybody add a new startup parameter to auto install plugins in 5.0.0?

### ISSUE THREAD

**Issue by himulawang** [docker-library/elasticsearch#126]
That will be much convenient.

Thanks!

**Comment by willfarrell** [comment]
I'm just using the following dockerfile to wrap this image.

```Dockerfile
FROM elasticsearch:5-alpine
RUN elasticsearch-plugin install x-pack
```

Seems clean enough. Plus this way I don't have to wait for plugin to install every time I launch a new container.

**Comment by tianon** [comment]
Indeed, what @willfarrell said is how I'd recommend handing this too -- combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with extra plugins installed.

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
