### ISSUE TITLE
When will Elasticsearch 5.0 GA be available ? <EOM>

### ISSUE THREAD

**Issue by ferronrsmith** [docker-library/elasticsearch#129]

**Comment by yosifkit** [comment]
Once we merge, build, and push https://github.com/docker-library/official-images/pull/2288.

**Comment by tianon** [comment]
Images are built and pushed now, just waiting for the signing system to kick them out on the `library/` image (which shouldn't take much longer -- I'd estimate less than an hour at the outside). :+1:
