### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by mausch** [docker-library/elasticsearch#13]
Is there any particular reason to use Java 7 instead of Java 8? Java 7 will stop being updated in April.

Until a few days ago I was using https://registry.hub.docker.com/u/dockerfile/elasticsearch/ , which uses Java 8, but it's not tagged and now it's deprecated.

I have a plugin that runs on Java 8 so I can't use this image as it is because of this.

**Comment by md5** [comment]
The reason is that this and many official images are based on Debian and
the OpenJDK 8 packages are only available in the Debian unstable release,
Sid.

The dockerfile image you were using is based on Ubuntu and installs
Oracle's JDK 8 from a PPA.

**Comment by mausch** [comment]
I see, thanks for the explanation. Is it in the plans to update this to the `8-jre` image after the Java 7 EOL?

**Comment by md5** [comment]
I haven't heard of any plans related to the Java 7 EOL, but I doubt the Debian situation will be sorted out by April. My understanding is that Java 8 will not land in a stable Debian version until Debian Stretch is released.

@tianon and I have discussed this a bit over at docker-library/java#29 in the context of creating `java:9-*` images.

**Comment by tianon** [comment]
Shortly after April 25th (
https://lists.debian.org/debian-devel-announce/2015/03/msg00016.html),
"stretch" should be created as the new testing.  Once that happens, the
"openjdk-8-jdk" package _should_ transition over, and our OpenJDK image
can/should do the same.

Irrespective of that, if _this_ upstream recommends Java 8 over Java 7,
then by all means, let's switch it, IMO.

**Comment by md5** [comment]
I'd be curious what @psftw has to say.

IMO, if Java 8 is not *required*, then it's not worth basing an official image on Sid just to use Java 8. I think having `jre8` variants of images as I've done with `jetty` seems OK, but they shouldn't be the default.

**Comment by md5** [comment]
BTW, great news @tianon about the likelihood of getting `openjdk-8-jdk` in Stretch this month.

**Comment by psftw** [comment]
A quick skim of the elasticsearch docs shows they recommend Oracle Java 1.8 for the latest releases (1.4, 1.5) and Oracle Java 1.7 for the older 1.3 release.  I think it makes sense to ship the upstream recommended 1.8 as the default.

**Comment by md5** [comment]
The upstream recommended 1.8 is Oracle's JDK, not OpenJDK. Do you think that makes a difference?

**Comment by psftw** [comment]
In my experience, it's really rare for something to depend exclusively on Oracle's Java, especially with 1.7 and later, and I don't think we have the option to ship Oracle's Java at this point anyway.  My understanding of Oracle's Java is that it is downstream from openjdk so they can bundle a few extra bits (debugging/monitoring/libraries) and offer support.  In the case of libraries, these are usually shipped with applications to get newer versions (embedde javascript engine come to mind).

**Comment by md5** [comment]
My experience with Oracle v. OpenJDK matches yours.

My personal reservation to the `elasticsearch` image using `openjdk-8-jre` is that it's still only available in Sid.

Part of the reason I bring this up is that I've seen reservations from Docker employees about Official Images based on Sid, particularly [this comment](https://github.com/docker-library/official-images/issues/569#issuecomment-83769946) by @ewindisch.

**Comment by psftw** [comment]
Yes, that makes sense.  FWIW, I agree that debian:sid should be avoided (but not banned) as a base image for other official images.  Up to this point, we've made heavy use of debian:jessie as well, which you could also argue should be avoided.

If I read the above correctly, then we could wait a few weeks and have a better-supported java 8 from Debian.  I don't see the harm in making the switch to jre8 now and then transparently having the Debian base change later.  The java runtime is its own giant abstraction with limited dependencies on underlying OS bits, but I'm not an expert on this to have a strong opinion, so here's an emoji for you: :tropical_fish:

**Comment by md5** [comment]
> If I read the above correctly, then we could wait a few weeks and have a better-supported java 8 from Debian. I don't see the harm in making the switch to jre8 now and then transparently having the Debian base change later.

Seems reasonable. Then again, it may be just as reasonable to wait until the first `debian:stretch` prerelease is available before switching to Java 8 if it's really going to happen this month.

@tianon What's the timeframe/dependencies on being able to create a `debian:stretch` image?

**Comment by tianon** [comment]
Jessie is scheduled to be released April 25th.  All we need after that is
the new "stretch" suite to start showing up on the mirrors.

**Comment by md5** [comment]
I just saw this today in an email to `java-debian` entitled "Jessie release notes for the Java packages":

> How to get Java 8 (backports or java-package)

I don't see a `jessie-backports` with an `openjdk-8-jre-headless` package in it and I'm not sure what `java-package` is, but this hints at the fact that it's at least possible in some straightforward way to install Java 8 on Jessie.

**Comment by md5** [comment]
Looks like `java-package` is used for creating Debian Java packages: https://packages.debian.org/jessie/java-package

It appears to only support Oracle's JDK though, so creating a Docker image that way may be problematic in terms of licensing.

**Comment by md5** [comment]
BTW, I just followed up on `debian-java` to ask about the backports option.

**Comment by md5** [comment]
And here was Emmanuel Bourg's helpful response:

> The jessie-backports repository isn't open yet, but once it's available
> we'll upload openjdk-8.

**Comment by ggtools** [comment]
Another solution would be to use a *generic* package for OpenJDK8 such as the one I build and push automatically to [bintray](https://bintray.com/clabouisse/obuildfactory-generic-x86-64/jdk-1.8.0-openjdk-x86_64/view)

**Comment by mausch** [comment]
`openjdk-8` is available now in [jessie-backports](http://backports.debian.org/changes/jessie-backports.html)

**Comment by md5** [comment]
Thanks @mausch! I've opened https://github.com/docker-library/java/pull/40 as a starting point.

**Comment by md5** [comment]
https://github.com/docker-library/java/pull/40 has been merged, so it should now be easy to create a PR to close this that will result in ES running under OpenJDK 8 on Debian Jessie.

**Comment by mausch** [comment]
See #30 , is that it? 
I double-checked just in case that `/etc/debian_version` shows "8.0". 
And `java -version` shows `openjdk version "1.8.0_45-internal"`

**Comment by mausch** [comment]
Cool, thanks folks.
