### ISSUE TITLE
ES_JAVA_OPTS doesn't override default options

### ISSUE THREAD

**Issue by EvgenyOrekhov** [docker-library/elasticsearch#130]
`-e ES_JAVA_OPTS="-Xms256m -Xmx256m"` doesn't have any effect, the process starts with
```
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms2g -Xmx2g
```
Update: I see `-Xms256m -Xmx256m` farther in the command, but it looks like it has no effect, because htop reports that Elasticsearch eats 560 MB of my memory.

**Comment by yosifkit** [comment]
>When using these settings, keep in mind that these settings are for the JVM's heap, and that the JVM can/will use more memory than just the size allocated to the heap. From Oracle's Documentation:
>
> Note that the JVM uses more memory than just the heap. For example Java methods, thread stacks and native handles are allocated in memory separate from the heap, as well as JVM internal data structures.
> http://stackoverflow.com/a/14763095

They are properly overriding options earlier in the command. When I set them to `512m`, it reserves about 700 MB and when I leave the default of `2g`, it reserves about 2300 MB.

**Comment by EvgenyOrekhov** [comment]
@yosifkit Thanks for the clarification.
