### ISSUE TITLE
Java memory error when building with Ubuntu

### ISSUE THREAD

**Issue by pfwd** [docker-library/elasticsearch#131]
I'm getting a memory error when running against Ubuntu 16.04.1 LTS 4.4.0-45-generic

This is in my docker-compose.ml

```
image: elasticsearch
environment:
    - ES_JAVA_OPTS=-Xmx10g -Xms10g
```

It doesn't matter what settings I add to ES_JAVA_OPTS as I always get the following error when running 

```
OpenJDK 64-Bit Server VM warning: 
INFO: os::commit_memory(0x0000000545330000,10650189824, 0) 
failed; error='Cannot allocate memory' (errno=12)

There is insufficient memory for the Java Runtime Environment to continue.

Native memory allocation (mmap) failed to map 10650189824 bytes 
for committing reserved memory.
```

**Comment by yosifkit** [comment]
Are you sure the system you are running this one has enough room for 10 GB of java heap space?

> When using these settings, keep in mind that these settings are for the JVM's heap, and that the JVM can/will use more memory than just the size allocated to the heap. From Oracle's Documentation:
>
>Note that the JVM uses more memory than just the heap. For example Java methods, thread stacks and native handles are allocated in memory separate from the heap, as well as JVM internal data structures.
> http://stackoverflow.com/a/14763095

**Comment by nguoianphu** [comment]
Can you try this ```sudo sysctl -w vm.max_map_count=262144```?

**Comment by canassa** [comment]
I am having the same issue, my Elasticsearch instance started failing since yesterday, I was running fine before that. Here is my error:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000085330000, 2060255232, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2060255232 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
```

I tried to add a ES_JAVA_OPTS to the docker environment variables, but that didn't help. I also tried to set the `vm.max_map_count` but that didn't help neither

**Comment by cristian04** [comment]
elasticsearch:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    command: sysctl -w vm.max_map_count=262144

docker-compose up elasticsearch
Starting myobtest_elasticsearch_1
Attaching to myobtest_elasticsearch_1
elasticsearch_1  | sysctl: setting key "vm.max_map_count": Read-only file system
myobtest_elasticsearch_1 exited with code 255

**Comment by yosifkit** [comment]
@cristian04, the sysctl for `vm.max_map_count` can only be done on the host, not in a container.

> the value of `vm.max_map_count` which is not namespaced and thus must be set to an acceptable value on the host
> \- [docker-library/docs/elasticsearch](https://github.com/docker-library/docs/tree/c6445a12d70ee6b8569c364df2bed859bc12aee4/elasticsearch#host-setup) (aka, source of Docker Hub readme)

**Comment by cristian04** [comment]
Oh, I see. Should I configure this change in my docker-machine right?

**Comment by blandflakes** [comment]
Also having this issue, but with a twist. We develop on macs. I've been screwing around with various settings, but can't for the life of me find the equivalent of:
`unknown oid 'vm.max_map_count'`

Instead, I get:
`unknown oid 'vm.max_map_count'`

**Comment by pfwd** [comment]
This is still an issue after running `sudo sysctl -w vm.max_map_count=262144`

The error is the same.
The host machine has 16GB of RAM.

This is working 'out of the box'  on my MacBook

**Comment by pfwd** [comment]
I've also removed the ES_JAVA_OPTS env memory options so its using default java heap space. 
Still having an issue:

    OpenJDK 64-Bit Server VM warning: INFO: 
    os::commit_memory(0x0000000085330000,   
    2060255232, 0) failed; error='Cannot allocate memory' (errno=12)
     #
     # There is insufficient memory for the Java Runtime Environment to continue.
     # Native memory allocation (mmap) failed to map 
    2060255232 bytes for committing reserved memory.
     # An error report file with more information is saved as:
     # /tmp/hs_err_pid1.log

**Comment by canassa** [comment]
I fixed my issue by passing the `ES_JAVA_OPTS` with a smaller value, I think that by default it tries to allocate the whole memory of the machine to it (in my case 2GB) and it fails.

**Comment by borger** [comment]
I'm having the same issue...

**Comment by evertramos** [comment]
@canassa could you share how did you pass it to your container?

**Comment by tianon** [comment]
I imagine something like `-e ES_JAVA_OPTS='-Xms1g -Xmx1g'` should work, right? (with higher or lower values depending on your available memory and how much you want to allocate to `elasticsearch` specifically)

**Comment by cblunt** [comment]
Had the same issued, but seems to be fixed with the following in `docker-compose.yml`:

```yml
  # docker-compose.yml
  elasticsearch:
    image: elasticsearch:5
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    mem_limit: '512m'
    volumes:
      - es_data:/usr/share/elasticsearch/data
```

(512m might be too small - I'm just starting with ES so testing different memory limits)

**Comment by tianon** [comment]
Indeed, using `ES_JAVA_OPTS` to configure memory usage of Elasticsearch is the proper way to solve this. :+1:

**Comment by carlosival** [comment]
This work for me in AMI AWS instances with only 1GB of memory.
sudo nano /etc/elasticsearch/jvm.options
-Xms512m
-Xmx512m

**Comment by n13** [comment]
Running a demo server on 512M machines, so I just removed the memory options / optimizations
sudo nano /etc/elasticsearch/jvm.options as follows: (thanks @carlosival )

# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space

# -Xms2g
# -Xmx2g

# explicitly set the stack size (reduce to 320k on 32-bit client JVMs)
#-Xss1m

With all memory options commented out, the JVM will simply do its thing and allocate memory as needed. I am guessing the reason the defaults are set is to optimize performance, and also to make memory use predictable (capped at 2g, so you can be sure it's not going to just run around allocating all memory on your server). But for my demo purposes none of that is needed.

**Comment by subokita** [comment]
The solution that worked for me:

Ran these on my host
```
docker-machine ssh
sudo sysctl -w vm.max_map_count=262144
```
Then I updated my docker-compose to this
```
elasticsearch-service:
        restart       : on-failure
        image         : docker.elastic.co/elasticsearch/elasticsearch:5.6.0
        ports         : 
            - 9200:9200
        networks      :
            - elknetwork
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
```

**Comment by dignizant** [comment]
This is still an issue after running sudo sysctl -w vm.max_map_count=262144

**Comment by sudeep225** [comment]
> I'm getting a memory error when running against Ubuntu 16.04.1 LTS 4.4.0-45-generic
> 
> This is in my docker-compose.ml
> 
> ```
> image: elasticsearch
> environment:
>     - ES_JAVA_OPTS=-Xmx10g -Xms10g
> ```
> It doesn't matter what settings I add to ES_JAVA_OPTS as I always get the following error when running
> 
> ```
> OpenJDK 64-Bit Server VM warning: 
> INFO: os::commit_memory(0x0000000545330000,10650189824, 0) 
> failed; error='Cannot allocate memory' (errno=12)
> 
> There is insufficient memory for the Java Runtime Environment to continue.
> 
> Native memory allocation (mmap) failed to map 10650189824 bytes 
> for committing reserved memory.
> ```

#You can Just increase the size of ram of the container you are running.
I had same problem with VM.
Now it is solved.

**Comment by pramodksahoo** [comment]
Add some space for swap area
$ free -m
$ sudo fallocate -l 1G /swapfile
$ sudo chmod 600 /swapfile
$ sudo mkswap /swapfile
$ sudo swapon /swapfile

**Comment by xmuwenxiang** [comment]
sudo sysctl -w fs.file-max=2097152
sudo sysctl -w vm.max_map_count=67108864

**Comment by dineshr93** [comment]
To increase the swap space https://askubuntu.com/a/1125418/269405

**Comment by ricardolira** [comment]
Make sure your host machine is not overloaded with any sort of PID consumming lots of memory. In my case I ran a top to check my server stats and I found out a postgres application was for some reason consumming > 200% CPU.. After some digging I found the issue and everything went back to normal.
