### ISSUE TITLE
ES5.0 ignoring commandline -Des.* options

### ISSUE THREAD

**Issue by spurdy-cvl** [docker-library/elasticsearch#132]
Hi,

This works in 2.4:

$ docker run -e ES_JAVA_OPTS="-Des.node.name=sean-set-this" --name=test -d elasticsearch:2.4
$ curl localhost:9200
...
  "name" : "sean-set-this",

This doesn't work in 5.0:

$ docker run -e ES_JAVA_OPTS="-Des.node.name=sean-set-this" --name=test -d elasticsearch:5
$ curl localhost:9200
...
  "name" : "-EHN3x_",

Command line looks OK inside image:
$ docker exec -it test /bin/bash -c "ps -eaf|grep java"
elastic+     1     0  1 14:47 ?        00:00:22 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms1600m -Xmx1600m -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Dio.netty.noUnsafe=true -XX:+HeapDumpOnOutOfMemoryError -Des.node.name=sean-set-this -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-5.0.0-alpha5.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch

Any ideas?

(also is that supposed to be elasticsearch-5.0.0-alpha5.jar in there?)

Thanks,

Sean Purdy

**Comment by spurdy-cvl** [comment]
Doing a workaround with "elasticsearch -E node.name" but I think the point stands.

**Comment by mcortinas** [comment]
Docker image in version 5.0 start ES loading params from files /etc/elasticsearch/jvm.options
In this file exist param such us JAVA_HEAP_and more....

**Comment by spurdy-cvl** [comment]
Yeah, that's what I'm trying to do.  -E options will work for now, but it seems odd if they've removed support for -Des.X.X at java run time.

**Comment by mcortinas** [comment]
Maybe @gerardorochin could help us with this? I'm not sure about this file would exist ont his path¿?

**Comment by jasontedor** [comment]
It's removed, in elastic/elasticsearch#18198.

**Comment by spurdy-cvl** [comment]
Thanks.  I guess it is in the combined change log for 5.0.0

Settings:
 Remove settings and system properties entanglement #18198 (issue: #18197) 

Just wasn't obvious, and not obvious to a non-programmer why you'd take the facility away.

Thanks again.

**Comment by jasontedor** [comment]
It's also in the [migration docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_packaging.html#_environmental_settings).

**Comment by mcortinas** [comment]
Hello,

 In order to the community knows better this change you can upload a basic jvm.options in https://github.com/docker-library/elasticsearch/tree/master/5.0/config

 What do you think?

Marc
