### ISSUE TITLE
Why is the configuration location '/usr/share/elasticsearch/config', not '/etc/elasticsearch' ?

### ISSUE THREAD

**Issue by erictt** [docker-library/elasticsearch#138]
I've checked the document : [https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html#deb-layout](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html#deb-layout)

It says, default configuration locations is `/etc/elasticsearch`, but why is it deferent in Docker?
I didn't see any updates in the `Dockerfile`.

And the tricky problem is x-pack configurations doesn't work if i put them under `/usr/share/elasticsearch/config`.

**Comment by yosifkit** [comment]
That only happens when using the init script:
```bash
NAME=elasticsearch
...
CONF_DIR=/etc/$NAME
...
DAEMON_OPTS="-d -p $PID_FILE -Edefault.path.logs=$LOG_DIR -Edefault.path.data=$DATA_DIR -Edefault.path.conf=$CONF_DIR"`
```

We run `elasticsearch` directly so it runs in the foreground, since there is no init system running in the container.  Thus, we just get the default `config` directory in the install directory.

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!

**Comment by unavailabl3** [comment]
If your Elasticsearch can't find hunspell dictionaries because there is no /etc/elasticsearch folder - just create folder with your hands `sudo mkdir /etc/elasticsearch/hunspell`
I don't know why, but ES is looking for hunspell only in /etc/elasticsearch
