### ISSUE TITLE
max file descriptors for elasticsearch process is too low

### ISSUE THREAD

**Issue by bitgandtter** [docker-library/elasticsearch#140]
Using Ubuntu 16.10
Docker 1.12.3
Docker Composer 1.8
Elastic latest tag

docker-compose.yml

  elastic:
      image: elasticsearch
      environment:
          - ES_JAVA_OPTS=-Xmx2g -Xms2g

getting on logs

elastic_1   | ERROR: bootstrap checks failed
elastic_1   | max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
elastic_1   | [2016-11-18T17:48:17,058][INFO ][o.e.n.Node               ] [HK_OIan] stopping ...

Any idea, thanks

**Comment by yosifkit** [comment]
That looks like the `vm.max_map_count` issue that was part of https://github.com/docker-library/elasticsearch/issues/98.  We added some info to the docs on how to fix it:
> **Note:** since 5.0, Elasticsearch only listens on `localhost` by default, so this image sets `network.host` to `0.0.0.0` (given that `localhost` is not terribly useful in the Docker context).
>
>As a result, Elasticsearch is more strict about the bootstrap checks that it performs, especially when checking the value of `vm.max_map_count` which is not namespaced and thus must be set to an acceptable value on the host (as opposed to simply using `--sysctl` on `docker run`).
>
> \- https://github.com/docker-library/docs/tree/master/elasticsearch#host-setup

**Comment by bitgandtter** [comment]
I follow the doc and i fix that config as mention for vm.max_map_count but on this case was for ulimits. i fix it with following config on my docker-compose.yml

ulimits:
          nofile:
              soft: 65536
              hard: 65536

**Comment by chovy** [comment]
this doesn't solve the problem for me.
