### ISSUE TITLE
ES 5.1.1 alpine cannot lock memory

### ISSUE THREAD

**Issue by jalberto** [docker-library/elasticsearch#154]
```
environment:                                                                                                                                          
  ES_JAVA_OPTS: "-Xms14g -Xmx14g"                                                                                                                     
  command: elasticsearch -Ecluster.name=vles -Ediscovery.zen.ping.unicast.hosts=es -Enode.master=true -Enode.data=true -        Enode.ingest=false -Ebootstrap.memory_lock=true
```

error:

```
[2017-01-12T10:20:09,941][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=12, reason=Out of memory
[2017-01-12T10:20:09,944][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM being swapped out.
[2017-01-12T10:20:09,944][WARN ][o.e.b.JNANatives         ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
[2017-01-12T10:20:09,944][WARN ][o.e.b.JNANatives         ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
        # allow user 'elasticsearch' mlockall
        elasticsearch soft memlock unlimited
        elasticsearch hard memlock unlimited
[...]
ERROR: bootstrap checks failed
memory locking requested for elasticsearch process but memory is not locked
```

probably that configuration is missing in the alpine base image?

**Comment by jalberto** [comment]
This same config was working on 5.0-alpine

**Comment by yosifkit** [comment]
> reason=Out of memory

You may need to change your limits or see what else on that server is using up your memory.

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
