### ISSUE TITLE
Add HEALTHCHECK instruction

### ISSUE THREAD

**Issue by ebuildy** [docker-library/elasticsearch#157]
HEALTHCHECK instruction (added in Docker 1.12) is very powerful and useful for data-base (because usually other containers will depend on). (more at https://blog.newrelic.com/2016/08/24/docker-health-check-instruction/).

This will tell if elasticsearch is up or not (not the container, but elasticsearch itself).

I think a simple

    HEALTHCHECK CMD curl --fail http://localhost:9200/ || exit 1

Could do the trick.

**Comment by yosifkit** [comment]
Copying comment from https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271

> I do not feel that generalized healthchecks on the official images are really that useful. 
>- users will have their own idea of what is "healthy"
>- it does not actually test that the service is listening to connections outside of `localhost` (see https://github.com/docker-library/healthcheck for some examples that do more than what's proposed here, including attempting to check whether the service is listening remotely)
>   - some of the Official Images even purposely start in a `localhost` only mode for database initialization and then kill and start the main service with full network availability
>- after upgrading their images, current users will have extra unexpected load on their systems for healthchecks they don't necessarily need/want and may be unaware of

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
