### ISSUE TITLE
Please do not stop maintaining these images. 

### ISSUE THREAD

**Issue by c4milo** [docker-library/elasticsearch#168]
Docker's images are way better crafted. ElasticCo's image is based on CentOS! nooooo

**Comment by tianon** [comment]
See https://github.com/docker-library/elasticsearch/pull/160 -- as part of the official images, we try very hard to stay as close to upstream's recommendations and preferences as possible.  In this case, upstream has requested that we stop maintaining these images altogether, and we're honoring that request.

The code here is open source, and you (or anyone else) are welcome to take it and continue to maintain your own ELK-stack images, but they will no longer be a part of the Docker Official Images program.  Thanks!
