### ISSUE TITLE
Build step failed.

### ISSUE THREAD

**Issue by meduri99** [docker-library/elasticsearch#170]
The build is failing with the following message: 
Step 12 : COPY config ./config

Starting phase: error
A build step failed: lstat config: no such file or directory

https://github.com/docker-library/elasticsearch/blob/8e87587ac5d6b44a8382a229162c88e65618c30a/2.4/Dockerfile#L8

**Comment by yosifkit** [comment]
You need to clone all the files in the repo with the `config` folder (and its contents) and `docker-entrypoint.sh` in order to build from the Dockerfile.
