### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by d1studio** [docker-library/elasticsearch#171]
version: '2'
services:
  elasticsearch-master:
    image: elasticsearch:5
  elasticsearch-node1:
    image: elasticsearch:5

error:
Creating network "elasticsearchdocker_default" with the default driver
Creating elasticsearchdocker_elasticsearch-node1_1 ...
Creating elasticsearchdocker_elasticsearch-master_1 ...
Creating elasticsearchdocker_elasticsearch-node1_1
Creating elasticsearchdocker_elasticsearch-master_1 ... done
Attaching to elasticsearchdocker_elasticsearch-node1_1, elasticsearchdocker_elasticsearch-master_1
elasticsearchdocker_elasticsearch-node1_1 exited with code 137

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
