### ISSUE TITLE
Please consider un-deprecating this image

### ISSUE THREAD

**Issue by cu** [docker-library/elasticsearch#176]
If you follow the links to the images maintained by elastic, you get images that come with something called x-pack: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html

X-pack comes with a 30-day trial, after which you must either subscribe/pay for it, or disable x-pack. This is a pointless extra step for those who just want elasticsearch only.

**Comment by yosifkit** [comment]
This was a decision by upstream and we respect their choice.

> As we fully support our images, I think that our preference would be that we use our infrastructure to deliver/support/maintain them. Our preference would be to deprecate this image and point to the official, fully-supported Elasticsearch images.
>
> \- jasontedor, elasticsearch maintainer (https://github.com/docker-library/elasticsearch/pull/160#issuecomment-281136686)

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

**Comment by tianon** [comment]
There's also a `-oss` variant of each image that doesn't contain X-Pack (see https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docker.html#_pulling_the_image for example).
