### ISSUE TITLE
DEPRECATED or not?

### ISSUE THREAD

**Issue by ddanier** [docker-library/elasticsearch#183]
Currently I feel like getting "mixed signals" about the deprecation of this repository.

https://hub.docker.com/r/library/elasticsearch/
https://store.docker.com/images/elasticsearch
--> No note about the deprecation (I'm sure it was there in the past)

Then I read: "This image will receive no further updates after 2017-06-20 (June 20, 2017)" or "The images found here will receive no further updates once the 6.0.0 release is available upstream."
But https://hub.docker.com/r/library/elasticsearch/tags/ clearly shows there have been updates 7 days ago, for version 6.4.x. This is very confusing.

https://github.com/docker-library/elasticsearch still shows the deprecation warning, but nobody using the "official repository" might probably look there.

I'm writing this as I am pretty sure the images have been moved over to https://www.docker.elastic.co/ and we should not use the docker hub/store images any more. I want to make sure others will get to that conclusion, too…without any confusion. I just had to discuss this with a colleague and had trouble finding the deprecation notice myself.

So please clarify things and make sure everybody has a fair chance to switch over to  https://www.docker.elastic.co/. Thank you!

**Comment by yosifkit** [comment]
Sorry, yes they were deprecated, but now they are being un-deprecated. We still need to remove some of the notices.

Elastic.co is now helping update the images available here, so any image in the 6 series is basically a copy of the images that are published on https://www.docker.elastic.co/. See https://github.com/docker-library/elasticsearch/pull/180 and https://github.com/docker-library/official-images/pull/4916 for more details

**Comment by ddanier** [comment]
Thanks for the clarification! 👍

**Comment by tianon** [comment]
I've updated the repo description, and applied https://github.com/docker-library/elasticsearch/commit/2bc77c615d6296684d255ae5892f21a3d1b5c0d5 to fix the `README`.  I'll be applying the same changes to Kibana shortly. :+1:
