### ISSUE TITLE
Any plan on 6.x alpine image release?

### ISSUE THREAD

**Issue by hustshawn** [docker-library/elasticsearch#186]
Any plan on 6.x alpine image release?

**Comment by jarpy** [comment]
No plan I'm afraid. Alpine is [not supported](https://www.elastic.co/support/matrix#matrix_os) by the upstream Elasticsearch product and has been shown to cause serious and [subtle problems](https://github.com/elastic/elasticsearch-docker/issues/44) with the Elasticsearch/JVM combination. Elastic has a [blog post](https://www.elastic.co/blog/docker-base-centos7) with a detailed explanation of the decision to focus on a CentOS base.

**Comment by tianon** [comment]
Thanks for clarifying (and for the excellent links). 👍❤️
