### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by vovimayhem** [docker-library/elasticsearch#19]
Hi! You did it again :) Another repo I don't need to maintain by myself anymore!

However, with my docker image I allowed the plugins folder to be mounted in the container, in the very same way the data folder can be mounted in a container using this official docker image.

Would this be the best way to add elasticsearch plugins? Or which is your recommended way of adding plugins to the container?

**Comment by yosifkit** [comment]
I am not sure what would be best.  They could just be copied or curled into the image using an automated build `FROM` this image, or they could be in a directory on the host and bind mounted in.  I assume the directory would be right next to the data dir, but it seems the package from their apt repo does not create a plugins directory anywhere.  Maybe we should create the directory?

Which option do you think would be better? Or maybe we add docs for both?

**Comment by andrewcstewart** [comment]
+1

**Comment by andrewcstewart** [comment]
Just FYI, here's a post describing one way to handle this: http://www.codedependant.net/2015/01/17/install-elastic-search-plugins-through-docker/

**Comment by md5** [comment]
The first versions of this image actually had an `elasticsearch.yml` file, but it was all comments and was removed after discussion here: https://github.com/docker-library/elasticsearch/pull/1#issuecomment-72969619

It seems like having a `/usr/share/elasticsearch/plugins` directory configured in `elasticsearch.yml` wouldn't be the worst idea, but users might get confused if they provide their own `elasticsearch.yml` and plugins stop working. This would have to be well documented.

Also, I didn't see anyone mention making this a `VOLUME` by default, but I'd be opposed to that personally.

**Comment by andrewcstewart** [comment]
@md5 I agree, I think volumes are a bad fit here.  I think that the Dockeronian way of doing this (did I just coin that term?) is to source the base elasticsearch image in a new Dockerfile with any additional the plugins:

```
FROM elasticsearch

RUN bin/plugin -install mobz/elasticsearch-head
```

etc..

**Comment by md5** [comment]
:+1:

**Comment by vovimayhem** [comment]
I'd be in favor of defining a mountable volume for plugins - the same way the data volume is mounted.

Also, advise to users that if they depend on specific plugins for their projects, they'd do much better to follow what @andrewcstewart instructs.

Add docs for both :) @yosifkit

**Comment by vovimayhem** [comment]
This would me more relevant given the fact that a default configuration was removed in [this discussion](https://github.com/docker-library/elasticsearch/pull/1#issuecomment-72969619)

Hence Elasticsearch would try the default paths described [there](http://www.elastic.co/guide/en/elasticsearch/reference/1.3/setup-dir-layout.html#default-paths) first, right?

**Comment by md5** [comment]
The default configuration file was all comments. What effect do you thing removing it would have?

**Comment by md5** [comment]
@vovimayhem I should have added that I'd assume you're right about the default paths. Have you tried doing as @andrewcstewart suggested?

**Comment by vovimayhem** [comment]
@md5: I can do what @andrewcstewart suggests, and it will surely work :)

Even if this image has not defined the plugins folder as a `VOLUME`, I can "force-mount" a volume in the container with plugins, and mount another elasticsearch.yml configuration file into the container... that's what I'm doing at [this ELK demo](https://github.com/vovimayhem/elk-stack-with-heroku-demo)

What I'm trying to discuss here is whether or not the plugins folder should be defined as a `VOLUME`. I know that your'e personally against it - I'm interested in your (and other's) opinion about "why" or "why not" :)

**Comment by md5** [comment]
The reason I'm against it being a volume is that it will prevent Dockerfiles like the one @andrewcstewart showed from working since it's not possible to undefine a `VOLUME`. In the case that someone does want a volume, it's easy to get one with `-v` or `--volumes-from`.

**Comment by md5** [comment]
Nice demo, BTW :+1:

**Comment by vovimayhem** [comment]
Good point, didn't saw it that way.

A little question (I know this is not the correct forum): What's the difference between defining volumes in the image and not doing it at all? "Force-mounting" volumes works pretty much the same, doesn't it?

**Comment by md5** [comment]
> A little question (I know this is not the correct forum): What's the difference between defining volumes in the image and not doing it at all? "Force-mounting" volumes works pretty much the same, doesn't it?

It's exactly the same.

**Comment by yosifkit** [comment]
Defining the volume prevents further build steps from persisting anything in that folder in the resulting image.  Build steps previous to the VOLUME definition can create data and the data will be available in the container unless you bind mount over it with `-v /host/dir:/volume/dir`.  VOLUME (or `-v /container/dir`) also makes docker do a bind mount anyway on docker run to a docker managed location (see `docker inspect` for where those are really stored).

**Comment by vovimayhem** [comment]
Boom! Didn't saw that coming also. Makes sense.

I can add something in the README doc to describe both methods.

I'd propose that adding it to the doc would close this issue.

**Comment by phantomwhale** [comment]
Was going to raise a separate issue, but given I'm doing what @andrewcstewart suggested above (https://github.com/docker-library/elasticsearch/issues/19#issuecomment-91650157) I thought I'd tag my observation here.

I am building a new docker image as follows:

```
FROM elasticsearch

RUN plugin -i elasticsearch/marvel/latest
```

And then when I run the docker image, the `/usr/share/elasticsearch/plugins` directory is empty. I can't see any volumes involved here, and apologise that I'm still quite new to Docker, but it appears this change is not being persisted when I start a new container.

So is this the recommended way to install new plugins? And is this behaviour (of plugins not being persisted) the same for other users?

**Comment by yosifkit** [comment]
@phantomwhale, using your two line `Dockerfile` seems to work fine here
```console
$ docker build .
Sending build context to Docker daemon 456.2 kB
Sending build context to Docker daemon 
Step 0 : FROM elasticsearch
 ---> 8f2207fb95ca
Step 1 : RUN plugin -i elasticsearch/marvel/latest
 ---> Running in dfdacbb82a9d
-> Installing elasticsearch/marvel/latest...
Trying http://download.elasticsearch.org/elasticsearch/marvel/marvel-latest.zip...
Downloading ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Installed elasticsearch/marvel/latest into /usr/share/elasticsearch/plugins/marvel
 ---> 3a4424379202
Removing intermediate container dfdacbb82a9d
Successfully built 3a4424379202
$ docker run -it --rm 3a4424379202 bash
root@245ac1789c5b:/# ls /usr/share/elasticsearch/plugins
marvel
root@245ac1789c5b:/# exit
$ docker run -it --rm 3a4424379202
[2015-07-16 21:41:26,966][INFO ][node                     ] [Grizzly] version[1.6.0], pid[1], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-07-16 21:41:26,967][INFO ][node                     ] [Grizzly] initializing ...
[2015-07-16 21:41:26,991][INFO ][plugins                  ] [Grizzly] loaded [marvel], sites [marvel]
...
```

**Comment by phantomwhale** [comment]
Yep, found out what idiotic thing I was doing - thanks for your comprehensive output @yosifkit - was using some scripts on top of docker which were starting the wrong container at the end of the process and these helped me track through it step by step

**Comment by tianon** [comment]
This appears to be fixed. :smile:
