### ISSUE TITLE
Update to 7.9.2

### ISSUE THREAD

**Issue by daveisfera** [docker-library/elasticsearch#195]
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.9.2.html

**Comment by wglambert** [comment]
It's commited https://github.com/docker-library/elasticsearch/commit/7bff32a5cb4329b1f826c80430070933731d457d
Waiting on an update PR https://github.com/docker-library/elasticsearch#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by tianon** [comment]
Thanks for the prod/reminder; PR is now up at https://github.com/docker-library/official-images/pull/8795 :+1:
