### ISSUE TITLE
Elasticsearch on Docker Hub outdated

### ISSUE THREAD

**Issue by ushuz** [docker-library/elasticsearch#196]
The latest tags on Docker Hub is still 7.10.1 and 6.18.3, 7.10.2 and 7.11.x is missing.
https://hub.docker.com/_/elasticsearch

**Comment by tianon** [comment]
There was a hiccup in the publishing of https://github.com/elastic/dockerfiles which was corrected in https://github.com/elastic/dockerfiles/pull/62, so the images will be updated following the merge of https://github.com/docker-library/official-images/pull/9758. :+1:
