### ISSUE TITLE
Logs volume

### ISSUE THREAD

**Issue by nrstott** [docker-library/elasticsearch#20]
I want to put my logfiles on a volume so that they are not in the image. As elasticsearch runs as the elasticsearch user, when I mount a volume at /usr/share/elasticsearch/logs, it can not create the log file. When I use bash in the container and chown the logs directory to `elasticsearch:elasticsearch` then restart the container, the log files are written as I would expect.

**Comment by md5** [comment]
See #18

**Comment by mi-hol** [comment]
@yosifkit would it make sense to close this too?

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
