### ISSUE TITLE
Broken update process

### ISSUE THREAD

**Issue by xeraa** [docker-library/elasticsearch#207]
We noticed that https://hub.docker.com/_/elasticsearch doesn't include the [latest images](https://github.com/elastic/dockerfiles/tags), namely 7.17.11, 7.17.12, 8.8.2, 8.9.0, and 8.9.1.

At first I wanted to open a PR similar to https://github.com/docker-library/official-images/pull/14895 but it looks like the update in this repository isn't working. And it seems to have happened right after https://github.com/docker-library/elasticsearch/commit/b57fb36f0db4f7969999ddf3781d55ec2e7210e5 (maybe @tianon remembers the context there).

The same problem is also happening in https://github.com/docker-library/kibana and https://github.com/docker-library/logstash. Let me know if I should open separate issues there.

**Comment by yosifkit** [comment]
We've let an Elastic team member know the problem in https://github.com/docker-library/official-images/issues/15091#issuecomment-1650635923. They have yet to fix the incorrect tags in their repo and continue to create more incorrect tags that all point to the same wrong commit:

https://github.com/elastic/dockerfiles/blob/v8.9.1/elasticsearch/Dockerfile
https://github.com/elastic/dockerfiles/blob/v8.9.0/elasticsearch/Dockerfile
https://github.com/elastic/dockerfiles/blob/v8.8.2/elasticsearch/Dockerfile
https://github.com/elastic/dockerfiles/blob/v7.17.12/elasticsearch/Dockerfile

**Comment by xeraa** [comment]
Oh, thanks! Let me see what we can do about that on our side 😅

**Comment by DaveSys911** [comment]
Seems to be an issue on our end commented on the original issue https://github.com/docker-library/official-images/issues/15091 Let's see if does it.

**Comment by DaveSys911** [comment]
Problem resolved for new images. We can close this and follow up  on https://github.com/docker-library/official-images/issues/15091 to publish the missed releases.

**Comment by xeraa** [comment]
Yeah, I was about to say since we already got complaints from users missing the 8.10 release on the official image :/

@DaveSys911 you'll be able to fix that again? 🥺
