### ISSUE TITLE
Container eats too much disk

### ISSUE THREAD

**Issue by Semyazz** [docker-library/elasticsearch#23]
I'm running this container on Ubuntu 14.04.2 with and docker 1.5.0 and it eats a lot of space over time.

`/dev/disk/by-label/cloudimg-rootfs` seems to eat all free space and the container stops to work.

Any idea what might be a cause? or where to look for more info?

**Comment by md5** [comment]
The `cloudimg-rootfs` label indicates that Docker and/or ES are using the same partition as your `/` mount.

Could you provide the output of `df`? Also, how are you running `elasticsearch`? Are you giving it a volume for `/usr/share/elasticsearch/data`?

**Comment by md5** [comment]
If you have given ES a dedicated directory for its data on a different disk than `cloudimg-rootfs`, my guess would be that the Docker logs are filling up the disk.

**Comment by jamesmr89** [comment]
I was running into something similar, seem to have solved it by using log_opt settings for max-size and max-files to ensure that docker rolls its logs appropriately...
