### ISSUE TITLE
multicast between different virtual machines

### ISSUE THREAD

**Issue by alexanderjardim** [docker-library/elasticsearch#25]
I have extended this image, exposing port 54328 for multicast. I am running 2 different vm's, each one with one container. But, none of the containers seem to find the other.

Here is my vagrantfile config for the network

```
      config.vm.define "node1" do |node1|
        node1.vm.network :private_network, :ip => "172.16.255.250"
        node1.vm.network "forwarded_port", guest: 9200, host: 10000
        node1.vm.hostname = "node1"
      end
      config.vm.define "node2" do |node2|
        node2.vm.network :private_network, :ip => "172.16.255.251"
        node2.vm.network "forwarded_port", guest: 9200, host: 11000
        node2.vm.hostname = "node2"
      end
```

This is my Dockerfile

```
    FROM elasticsearch
    EXPOSE 54328
```

This is the command I am using to start the containers on each vm

```
sudo docker run -d -p 9200:9200 -p 54328:54328 -p 9300:9300 elasticsearch-multicast
```

Is there anything I am forgeting to do?

**Comment by md5** [comment]
I haven't played around with this myself, but my understanding is that multicast between containers on different hosts (including different VMs) does not work. This may be relevant: https://github.com/docker/docker/issues/3043

**Comment by scrisenbery** [comment]
@md5 Was this a problem with multicast or with Docker's networking. I'm using Kubernetes so each container has it's own IP, but I am still running into issues. Unicast isn't really an option though because a container won't have the same IP every time.

**Comment by markwalkom** [comment]
FYI we (Elastic) dropped multicast by default from Elasticsearch 2.X and it's now a plugin.
We don't recommend it for production deployments either.

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
