### ISSUE TITLE
New feature request: Docker files for Power platform (SLES, RHEL, Ubuntu).

### ISSUE THREAD

**Issue by ChristinaGandham** [docker-library/elasticsearch#28]
Hi,

I have written dockerfile for building Logstash from source and to run the test cases. I have built and tested the source code available on git successfully through the dockerfile for PPC64LE architecture. The dockerfile is successfully run on following platforms:
Ubuntu 14.10
SUSE Linux 12.0
RHEL 7.1

Kindly suggest me where can I (which repository) contribute this dockerfile for Logstash.

Regards,
Christina

**Comment by yosifkit** [comment]
It would be awesome to have multiple architectures for the official images.  Unfortunately docker, the Docker Hub, and the Official Images program only officially support amd64 images, but hopefully this will change in the near future.

But if you are looking for the official image git repo for logstash, it is over [here](https://github.com/docker-library/logstash).

**Comment by ChristinaGandham** [comment]
Hi,

I would like to contribute logstash dockerfile for power architecture by adding (_ppc64le) suffix in the file name.
Request you to please comment on the above suggestion for uploading dockerfiles for power architecture.

Regards,
Christina

**Comment by yosifkit** [comment]
Please see the current initiative: https://github.com/docker-library/official-images/tree/master/#architectures-other-than-amd64

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
