### ISSUE TITLE
Automatically set `network.publish_host` during startup

### ISSUE THREAD

**Issue by arabold** [docker-library/elasticsearch#31]
From my understanding this docker image cannot be used in a cluster environment as the instances are exposing their internal IP address (of the container) rather than the one of the host. So this will simply not work out of the box. I've played with various solutions, e.g. passing "-Des.network.publish_host=..." when invoking the `docker run` command, but it's cumbersome.

Therefore I suggest to update the `docker-entrypoint.sh` to automatically set the `network.publish_host` config setting during startup. This should make things a lot easier for everybody.

Something like this should work:
```bash
#!/bin/bash

set -e

NETWORK_PUBLISH_HOST=${NETWORK_PUBLISH_HOST:-`/sbin/ip route|awk '/default/ { print $3 }'`}

# Add elasticsearch as command if needed
if [ "${1:0:1}" = '-' ]; then
	set -- elasticsearch
fi

# Drop root privileges if we are running elasticsearch
if [ "$1" = 'elasticsearch' ]; then
	# Change the ownership of /usr/share/elasticsearch/data to elasticsearch
	chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data
	exec gosu elasticsearch "$@" -Des.network.publish_host=$NETWORK_PUBLISH_HOST
fi

# As argument is not related to elasticsearch,
# then assume that user wants to run his own process,
# for example a `bash` shell to explore this image
exec "$@"
```

This way it would be even possible to overwrite the host by providing a `NETWORK_PUBLISH_HOST` environment variable.

Any thoughts or suggestions?

**Comment by ggtools** [comment]
I don't think this is a good thing to do as it assumes that the connection to the elasticsearch server will be done through the *EXPOSE*d ports which is not the case if you are using `--link`.

On one hand have the current elasticsearch container listen to the host IP is pretty simple by adding the right `-Des.network.publish_host` option on the command when creating the elasticsearch container or by creating a `config.yml`. 

On the other end, with this change, with this change it'll be almost impossible to have the elasticsearch server listen to the container ip without having to change the `docker-entrypoint.sh`.

**Comment by arabold** [comment]
You're probably right, @ggtools. I'm running into an issue here with my setup as well - using the `config.yml` seems to be more robust

**Comment by ebuildy** [comment]
Docker container can bind on the host IP.

`docker run --net=host .....`

If you want a cluster, you should use first a tool like Mesos with Marathon (https://github.com/mesosphere/marathon).

**Comment by tianon** [comment]
Agreed, this definitely isn't something we should be configuring by default. :+1: (sorry for the massive delay!)
