### ISSUE TITLE
How to install plugin?

### ISSUE THREAD

**Issue by Gwill** [docker-library/elasticsearch#32]
How to install plugin?

I have config like this http://www.codedependant.net/2015/01/17/install-elastic-search-plugins-through-docker/ .

And when I have finished install plugin(the plugin files is already in volume path), i start ES, request plugin it return 400.

**Comment by yosifkit** [comment]
That walkthrough is for `dockerfile/elasticsearch`, not the official image `elasticsearch`.  You will probably just need to change all the container paths from `/data` to `/usr/share/elasticsearch/data`.  I am not entirely sure on the config file placement since there is a `/usr/share/elasticsearch/config` directory.

**Comment by Gwill** [comment]
So how to install plugin?

**Comment by ebuildy** [comment]
You can use `docker exec` or create your own Docker image, that overrides this one.

Then refer to traditional elastic documentation to see the plugin installation syntax.

**Comment by wgriffiths** [comment]
Heres an example of how I  installed the head plugin

1. Start container with volume for plugins and es as its name

```
docker run -d -P  -p 9200:9200 -p 9300:9300 --name "es" -v "$PWD/es/plugins":/usr/share/elasticsearch/plugins elasticsearch 
```

2. Install head plugin

```
docker exec es /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head
```

Hope this helps

**Comment by Gwill** [comment]
@wgriffiths , Thanks!

**Comment by iHeeMo** [comment]
@wgriffiths you should execute the second command as follows 

`docker exec es /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head`

Hope this helps

**Comment by nuest** [comment]
After the last comment here, an official blog post was published:

https://www.elastic.co/blog/elasticsearch-docker-plugin-management

Hope this helps

**Comment by harobed** [comment]
I'm suggest to append this link ( https://www.elastic.co/blog/elasticsearch-docker-plugin-management ) in README

**Comment by lambdaq** [comment]
In case anyone else is running the latest container

    docker pull elasticsearch

Somehow the command was changed to `/usr/share/elasticsearch/bin/elasticsearch-plugin`

**Comment by yosifkit** [comment]
Looks like the change from `plugin` -> `elasticsearch-plugin` was back in 5.0. Note that `/usr/share/elasticsearch/bin/` is in the PATH on all of the images, so you can use `plugin` on the 1 and 2 series and `elasticsearch-plugin` on 5 and up.

**Comment by dixon1e** [comment]
The executable path is correct, but the plugins themselves are not found. Docs say these plugins were moved into X-Pack: https://www.elastic.co/guide/en/marvel/current/installing-marvel.html

**Comment by henrywallace** [comment]
I ran into this same problem with elasticsearch:5.6. For prosperities sake, here's how I debugged the problem:

I had a docker file
```
FROM elasticsearch:5.6

COPY my-plugin.zip /
RUN /usr/share/elasticsearch/bin/plugin install file:///my-plugin.zip
```

But, I would get the following
```
$ docker build . -t elasticsearch:my-plugin
Sending build context to Docker daemon  24.37MB
Step 1/5 : FROM elasticsearch:5.6
 ---> 9b44bde11dd8
Step 2/5 : COPY my-plugin.zip /
 ---> Using cache
 ---> a27fd93eddb0
Step 3/5 : RUN /usr/share/elasticsearch/bin/plugin install file:///my-plugin.zip
 ---> Running in 78ccd46dcc6b
/bin/sh: 1: /usr/share/elasticsearch/bin/plugin: not found
The command '/bin/sh -c /usr/share/elasticsearch/bin/plugin install file:///my-plugin.zip' returned a non-zero code: 127
```

So I took the intermediate hash `a27fd93eddb0` and did the following:
```
$ docker run --rm --it a27fd93eddb0 sh
# bash
# root@43211f8792a3:/usr/share/elasticsearch# ls -h /usr/share/elasticsearch/bin/
elasticsearch			elasticsearch-plugin			elasticsearch-translog
elasticsearch-keystore	elasticsearch-systemd-pre-exec	elasticsearch.in.sh
```

Thar she blows!

**Comment by olidaver** [comment]
> @wgriffiths the second command depends on your elasticsearch version
> if you are using `2.0` then use the same command without the dash character before `install`
> `docker exec es /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head`
> 
> Hope this helps

Thank you, vefy helpful for me.

**Comment by worldsayshi** [comment]
In later versions `/usr/share/elasticsearch/bin/plugin` has been changed to `/usr/share/elasticsearch/bin/elasticsearch-plugin`.
