### ISSUE TITLE
Executable file not found in $PATH

### ISSUE THREAD

**Issue by bargenson** [docker-library/elasticsearch#36]
Hi,

I want to start an elasticsearch:1.6 container but when I try to run `docker run -ti elasticsearch:1.6`, I get the following error: `error: exec: "elasticsearch": executable file not found in $PATH`

I'm using:
> Client version: 1.6.1
> Client API version: 1.18
> Go version (client): go1.3.3
> Git commit (client): a8a31ef/1.6.1
> OS/Arch (client): linux/amd64
> Server version: 1.6.1
> Server API version: 1.18
> Go version (server): go1.3.3
> Git commit (server): a8a31ef/1.6.1
> OS/Arch (server): linux/amd64

> Storage Driver: btrfs
> Execution Driver: native-0.2
> Kernel Version: 3.8.13-68.1.2.el6uek.x86_64
> Operating System: Oracle Linux 6.6

It's working correctly on my MacBook using boot2docker with Docker 1.4.1.

Any idea?

**Comment by yosifkit** [comment]
I can't reproduce here. Have you tried doing a `docker pull elasticsearch:1.6`?

**Comment by bargenson** [comment]
Yes, it doesn't help. 

After more tests, I think the issue comes from the hardening script we are using on that machine... Probably because of one (or several) umask configuration(s) that we use. 
I'm trying to test again with a 022 umask for the Docker daemon.

**Comment by thogg4** [comment]
@bargenson did you figure this out? i think im having the same issue.

**Comment by bargenson** [comment]
Yes. Sorry, I didn't close the issue. If I remember correctly, the issue was because my machine was using a too much restrictive umask. Because of that, some permissions of my elasticsearch containers were screwed. 
I fixed that changing the umask level in the docker service script.

**Comment by Orabig** [comment]
I have the very same issue, and don't know how to "change the umask level". :/
Some help or more precise clues would be very helpful...

**Comment by cggaurav** [comment]
This happens when you expose volume /usr/share/elasticsearch in Tutum. FYI.
