### ISSUE TITLE
Clarification in "How to use this image"

### ISSUE THREAD

**Issue by ArmandGrillet** [docker-library/elasticsearch#39]
The documentation states that `This image includes EXPOSE 9200 9300 (default http.port), so standard container linking will make it automatically available to the linked containers.`.

However, when running the first command in the doc, `docker run -d elasticsearch`, the container's ports are not published to the host. What I mean is that `curl 127.0.0.1:9200` returns `curl: (7) Failed to connect to 127.0.0.1 port 9200: Connection refused`. 

Thus wouldn't it be better to have the command `docker run -p 9200:9200 -p 9300:9300 -d elasticsearch` instead of  `docker run -d elasticsearch` in the doc as it seems the standard use case of this image? With this command, `curl 127.0.0.1:9200` returns info.

**Comment by ggtools** [comment]
IHMO publishing port should be part of the background knowledge of users. Since the `curl` command is not part of the documentation putting the `-p` options in the command might raise some questions like *why is it needed to publish the ports?*

**Comment by ArmandGrillet** [comment]
@ggtools I'm starting with elasticsearch so this may sounds stupid, but what can you do by simply running `docker run -d elasticsearch`? In all the tutorials that I read so far the published port `9200` is needed, even the [official installation steps](https://www.elastic.co/downloads/elasticsearch).

**Comment by ggtools** [comment]
Actually if you are using your elasticsearch container in another container using the `--link` mechanism, you don't need to publish the ports.

**Comment by yosifkit** [comment]
You only need to publish ports if you need to access it outside of the machine running docker.  If you are on linux, you can access the container by hitting its ip address (`curl "$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' myContainerNameOrId):9200"`).

**Comment by ArmandGrillet** [comment]
Oh ok, thank you both for your explanations and sorry for this useless issue.

**Comment by yosifkit** [comment]
No problem. Maybe it will help someone in the future too. :smile:

**Comment by bac** [comment]
@yosifkit It did.  Thanks.  :)

**Comment by Kerruba** [comment]
Yep actually was helpfull @ArmandGrillet and @yosifkit
