### ISSUE TITLE
How initialize with some mappings or templates?

### ISSUE THREAD

**Issue by ebuildy** [docker-library/elasticsearch#44]
Hello,

I would like to be able to set some templates and mapping if they are not present yet in ES data. What the best way to achieve it?

(To me, the difficult part is to wait that elasticsearch has been started & ready).

Thanks you,

**Comment by yosifkit** [comment]
The way we do it in the mysql image is to repeatedly try connecting with a timeout ([entrypoint](https://github.com/docker-library/mysql/blob/fa632dc9b955f58650fc2ad3e1bb971b5e92816f/5.6/docker-entrypoint.sh#L32-L38)).  It should be a similar setup to try until elasticsearch is available.

**Comment by santiagopoli** [comment]
I have the same question. I need to initialize the mappings, what would be the best approach to achieve this?

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
