### ISSUE TITLE
Data volume is not actually used by ElasticSearch

### ISSUE THREAD

**Issue by JamesHarrison** [docker-library/elasticsearch#47]
Hi,

ElasticSearch defaults to putting data in `/var/lib/elasticsearch/<clustername>`.

While `/usr/share/elasticsearch/data` is set up properly in the Dockerfiles/entrypoint, nowhere is there any configuration telling ElasticSearch to actually use it. As such, following the instructions in the README to store your data on a host/attached volume won't actually put your data in the mapped volume.

If you're really unlucky/stupid you'll only notice this after waiting for an hour or two for an import job to run.

**Comment by md5** [comment]
Are you sure about this?

I see this message when ES starts up:

```console
[2015-08-26 13:29:18,964][INFO ][env                      ] [Medusa] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [173.4gb], net total_space [191.1gb], types [ext4]
```

**Comment by md5** [comment]
Are you buy any change using `docker-machine` or `boot2docker` (or otherwise using a VM)? If so, you won't see the data on the host filesystem if it's not under `/Users` on OS X or `C:\Users` on Windows. Instead, it will live at the specified path inside the VM.

**Comment by JamesHarrison** [comment]
Sorry, I'm an idiot - the config file I'm using puts data in /var/lib/elasticsearch. I've never configured that manually so I assume it's a Debian packaging consideration. My bad!

**Comment by md5** [comment]
Glad you figured it out! :+1:
