### ISSUE TITLE
It's currently hard to use custom config settings with official elasticsearch images

### ISSUE THREAD

**Issue by mamikonyana** [docker-library/elasticsearch#53]
Currently the config for logging is being copied into the image before it is being uploaded to docker hub so in order to change the configs one has to manually add that instruction to their docker file.

I propose adding ONBUILD instruction in front of the `COPY config...` command so that it would be much easier to reuse official elasticsearch images. see #34 for a suggested implementation. This is very similar to python onbuild images where `requirements.txt` is being copied onbuild and saves users time.

**Comment by tianon** [comment]
Copying my comment (https://github.com/docker-library/elasticsearch/pull/34#issuecomment-173709015) here so we can discuss here cohesively:

I'm not sure I understand what benefit this provides over just bind-mounting the config folder, or adding a simple `COPY` line to your own dependent `Dockerfile` to add it in (ie, `FROM elasticsearch` / `COPY config /usr/share/elasticsearch/config`)?  Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with your own custom config.

**Comment by mamikonyana** [comment]
This was a while ago, I might not remember all the reasoning aside from what I had written, but the gist of it is not to write the same (COPY) instruction again if it could be avoided by adding ONBUILD before it.

**Comment by tianon** [comment]
Well, with ONBUILD here, we don't get the original copy for the default
configuration (which is what it's here for).

**Comment by mamikonyana** [comment]
ok.
