### ISSUE TITLE
Cannot pull elasticsearch

### ISSUE THREAD

**Issue by vorobey** [docker-library/elasticsearch#57]
Trying to pull elasticsearch, but get HTTP400 error

```
Pulling elasticsearch (elasticsearch:latest)...
Pulling repository docker.io/library/elasticsearch
d3aa5ff744e2: Error pulling image (latest) from docker.io/library/elasticsearch, HTTP code 400ps://registry-1.docker.io/v1/, HTTP code 400
8c00acfb0175: Download complete
8b49fe88b40b: Download complete
3bdf542c6cd7: Download complete
f25aff3c52d8: Download complete
1ae6b34191f6: Download complete
52d86395a92b: Download complete
ac33986dcda9: Download complete
7c66bfc43ad9: Download complete
bf5d4aae4686: Download complete
6707c13cc6f0: Download complete
81f1a5272622: Download complete
fd1daccb2022: Download complete
b4789d59ed14: Download complete
7b2de77edf80: Download complete
f5b215df68c4: Download complete
1b1bf86e647f: Download complete
d25acb534819: Download complete
be00ef0a0c4e: Error pulling dependent layers
Error pulling image (latest) from docker.io/library/elasticsearch, HTTP code 400
```

Got this error also for mongo for few days, but today i pulled mongo

**Comment by webrmedia** [comment]
2nd the issue, but we're getting a HTTP 500 error.

```
2015/09/21 14:13:04 Error pulling image (latest) from elasticsearch, Server error: Status 500 while fetching image layer
```

**Comment by yosifkit** [comment]
related issue: https://github.com/docker-library/mongo/issues/54

**Comment by tianon** [comment]
> This usually means a [problem with Docker Hub](https://twitter.com/dockerstatus/status/645548753978396672). If you don't see anything on https://status.docker.com/ or https://twitter.com/dockerstatus, I would suggest opening a ticket with support@docker.com or tweeting at dockerstatus.  We only maintain the images and do not have control or access to the distribution system (Docker Hub).

**Comment by shredding** [comment]
I had this today as well, so if you are really hopeless and need this image, `1.7.2` download works.
