### ISSUE TITLE
Can't connect to elasticsearch:2

### ISSUE THREAD

**Issue by blacktop** [docker-library/elasticsearch#58]
It doesn't seem to bind the same as the `latest` version, it is using 127.0.0.1 and not 0.0.0.0

**Comment by blacktop** [comment]
starting it like this fixes it:
```bash
$ docker run -d --name es -p 9200:9200 elasticsearch:2 -Des.network.host=0.0.0.0
```

**Comment by zhaozhiming** [comment]
You saved me, thank you.

**Comment by yosifkit** [comment]
Yeah, upstream changed the default in the new beta releases.

**Comment by amsdard** [comment]
I can't find what -D for docker run does. Can anyone explain what it does?

**Comment by yosifkit** [comment]
Since it is after the image name, the `-D` here is being passed to the elasticsearch container, not to docker.

**Comment by dansantner** [comment]
Thanks @yosifkit.  That one got me out of the gate!

**Comment by cromulus** [comment]
Is there any reason that the default listen address should be 127.0.0.1? Seems like the older behavior was a more sensible default...

**Comment by wernight** [comment]
Immediate simple fix would be to have `-Des.network.host=0.0.0.0` be the default `CMD`. Better fix for later would be to have `sed` the default config or something similar.

**Comment by tianon** [comment]
Thanks for the report -- this is a duplicate of #52. :+1:  (Closing so we can track it in one place.)
