### ISSUE TITLE
Shield being installed in the wrong directory

### ISSUE THREAD

**Issue by wprl** [docker-library/elasticsearch#79]
This may be a shield issue.  After several hours trying to figure out why authentication wasn't working, I noticed there are two config directories in my elasticsearch container.  The shield data files are installed in `/etc/elasticsearch` but they need to be in `/usr/share/elasticsearch/config/`.  

To solve this I moved the shield directory to the right location.  Wondering if there is a better solution…

``` Dockerfile
FROM elasticsearch:2.1.1

# Add custom roles config
ADD ./roles.yml /etc/elasticsearch/shield/roles.yml

# Install Shield
RUN /usr/share/elasticsearch/bin/plugin install license
RUN /usr/share/elasticsearch/bin/plugin install shield

# Create user 
RUN /usr/share/elasticsearch/bin/shield/esusers useradd abc -r abc -p xyzxyz

# Move shield files to the right location
RUN mv /etc/elasticsearch/shield /usr/share/elasticsearch/config/shield
```

**Comment by rsingh2411** [comment]
Hi This si not working with given workaround also its throwing an authentication error

**Comment by rsingh2411** [comment]
I was able to use this fix and it worked, only thing this time around i did was used above docker file as mentioned by William, 

Earlier i was using the standard elastic search docker file which had step from java installation and installing elastic search binary, then added plugins installation, I wonder why didn't that work. as in above docker file we are extending the same  standard elastic search docker file

**Comment by ldavidson** [comment]
I may be seeing the same issue

**Comment by baboune** [comment]
I have the same issue.  And the "fix" of moving 
RUN mv /etc/elasticsearch/shield /usr/share/elasticsearch/config/shield
Does not work:

> 
> ERROR: The configuration directory [/etc/elasticsearch/shield] does not exist. The esusers tool expects Shield configuration files in that location.
> The plugin may not have been installed with the correct configuration path. If [/usr/share/elasticsearch/config/shield] exists, please copy the shield directory to [/etc/elasticsearch]

**Comment by rv-gava** [comment]
Guys, the same problem and the same workaround works for me!

**Comment by easyrasta** [comment]
+1 same issue, workaround didn't work for me

**Comment by OscarBarrett** [comment]
Moving the shield directory worked fine for me (using `elasticsearch:latest`). Make sure you add a user as well. I call the following before moving the directory:

    /usr/share/elasticsearch/bin/shield/esusers useradd $ES_USERNAME -r admin -p "$ES_PASSWORD"

**Comment by up9cloud** [comment]
mount the config dir both to the `/etc/elasticsearch` and `/usr/share/elasticsearch/config` should work fine.

```sh
docker run -d \
-v /path/to/config:/etc/elasticsearch \
-v /path/to/config:/usr/share/elasticsearch/config \
elasticsearch:2
```

**Comment by shrenikgala** [comment]
Will this workaround work if you want to create a new user after you have moved your shield files to /usr/share/elasticsearch/config/shield

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
