### ISSUE TITLE
Git versions don't match tags in dockerhub

### ISSUE THREAD

**Issue by renewooller** [docker-library/elasticsearch#81]
Currently this could happen:
1. I set elasticsearch up on a docker host in my production environment using the image from dockerhub. Works fine.
2. Someone makes a breaking change in github without my knowledge and publishes it to dockerhub, overwriting the image that I had previously pulled down. IE it may pass their tests but fail for my configuration.
3. Production server restarts for some reason. Docker, noticing that the remote version with the same tag is different, pulls down the latest version with the breaking change, breaking the production server.  

This happened to me recently when using the 'official' rmq dockerhub image, so now we keep our own version in our own docker repo - I'd prefer not to have to do this though. 

A way around it would be to use tags that indicate the version on github, either an explicit version or commit hash. This way when someone does a change in github, it will be reflected in dockerhub.

The tags used in dockerhub could be something like 2.2 (elasicsearch version) - a4fe2 (dockerfile commit hash)

What do ye think about this?

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

For more information, please see https://github.com/docker-library/elasticsearch/pull/160, https://github.com/docker-library/docs/pull/842, and https://github.com/docker-library/docs/pull/945.

> This image has been deprecated in favor of the [official `elasticsearch` image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

Thanks!
