### ISSUE TITLE
Unexpected result using relative path with `VOLUME`

### ISSUE THREAD

**Issue by webwurst** [docker-library/elasticsearch#87]
This [change](https://github.com/docker-library/elasticsearch/commit/8a74bd1f706af238e2cb9d8063d5067338e5d388#diff-d78ec566026bd329a607140273165923L45) does not work for me as expected:
```
-VOLUME /usr/share/elasticsearch/data
+VOLUME ./data
```

Inspecting resulting container shows up like this:
```
{
  "Name": "63cf3dbc86f43f34f3758064810c426f2711788514aaeb681d92f87b97faec39",
  "Source": "/var/lib/docker/volumes/63cf3dbc86f43f34f3758064810c426f2711788514aaeb681d92f87b97faec39/_data",
  "Destination": "data",
  "Driver": "local",
  "Mode": "",
  "RW": true,
  "Propagation": ""
}
```

There is no absolute path for destination. And within the container mount shows this:
```
/dev/vda1 on /data type ext4 (rw,relatime,data=ordered)
```
instead of `/usr/share/elasticsearch/data`.

**Comment by djmaze** [comment]
I think this is a bug in Docker. Relative `VOLUME` declarations should either become relative to the `WORKDIR` or raise an error instead.

**Comment by djmaze** [comment]
Reported at https://github.com/docker/docker/issues/20988.

**Comment by iDuuck** [comment]
I am also getting an `should be absolute` error using docker-compose:
```
ERROR: Invalid bind mount spec "/mnt/sda1/var/lib/docker/volumes/3a55e936b6e82851a119406fcb4d9d27a8b06381db4d1f6f9af55ed1d5ba914f/_data:data:rw": volumeabs: Invalid volume destination path: 'data' mount path must be absolute.
```

**Comment by geowa4** [comment]
The only way I could think to get around this issue with Docker Compose is to copy the code to build the Docker image into my project source, which is by no means ideal. Changing `VOLUME ./data` to `VOLUME /usr/share/elasticsearch/data` worked. I recommend switching to that so people can work without building all their own images.

**Comment by Bordovsky** [comment]
Hi. Could you push changes from this on Docker Hub? It driven me crazy that it is fixed and on my machine it is still wrong, until I saw that Docker Hub have 8 days old update :-)

**Comment by iDuuck** [comment]
For temporary fix you could just pull that Dockerfile into your project and use it with the `build: .` command.

**Comment by yosifkit** [comment]
Sorry, hadn't done a PR to official images yet. Should be merged shortly (and then the build server will build it thereafter): https://github.com/docker-library/official-images/pull/1532.
