### ISSUE TITLE
showed "failed recovery" after upgrade elasticsearch from  2.0 to 2.2

### ISSUE THREAD

**Issue by Tily-wlx** [docker-library/elasticsearch#92]
For same reasons, i need upgrade my ELK docker images to latest, it showed many error info from elasticsearch logs, Could tell any one tell me the reason, Thanks a lot.

***sandal-es | [2016-03-21 01:59:08,491][WARN ][indices.cluster          ] [Arc] [[.kibana][0]] marking and sending shard failed due to [failed recovery]***
sandal-es | [.kibana][[.kibana][0]] IndexShardRecoveryException[failed recovery]; nested: IllegalStateException[Checkpoint file translog-3.ckp already exists but has corrupted content expected: Checkpoint{offset=46155, numOps=31, translogFileGeneration= 3} but got: Checkpoint{offset=43, numOps=0, translogFileGeneration= 3}];
sandal-es | 	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179)
sandal-es | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
sandal-es | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
sandal-es | 	at java.lang.Thread.run(Thread.java:745)
***sandal-es | Caused by: java.lang.IllegalStateException: Checkpoint file translog-3.ckp already exists but has corrupted content expected: Checkpoint{offset=46155, numOps=31, translogFileGeneration= 3} but got: Checkpoint{offset=43, numOps=0, translogFileGeneration= 3}***
sandal-es | 	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:339)
sandal-es | 	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
sandal-es | 	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208)
sandal-es | 	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151)
sandal-es | 	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
sandal-es | 	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1510)
sandal-es | 	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1494)
sandal-es | 	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:969)
sandal-es | 	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:941)
sandal-es | 	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
sandal-es | 	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
sandal-es | 	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
sandal-es | 	... 3 more

**Comment by yosifkit** [comment]
Did you follow the upgrade steps that elasticsearch recommends? https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html

Looking over those instructions, you may need a volume on `config` and `plugins` as well; which can be added on the docker run with `-v /local/path/:/usr/share/elasticsearch/config/` (might also need `config/scripts/`?).  You will probably need to `docker cp` the contents of those folders from your old container to your host so that you can bind mount them to the new container.

**Comment by Tily-wlx** [comment]
Thanks for your reply, In fact i have only one node, So it may not be the solution for my problem, but i will have a try.

**Comment by tianon** [comment]
Closing since this doesn't sound like an issue with the image (and @yosifkit provided a useful pointer for future travellers having a similar problem). Thanks! :+1:
